---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-anomaly-detector
  labels:
    app: prometheus-anomaly-detector
    operated-prometheus: 'true'
spec:
  selector:
    app: prometheus-anomaly-detector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics
